<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416112159 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hike_done (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, done_at DATE NOT NULL, hiker_id INT NOT NULL, hikesdone_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_94B46DD913D51EC0 ON hike_done (hiker_id)');
        $this->addSql('CREATE INDEX IDX_94B46DD9569FDE7D ON hike_done (hikesdone_id)');
        $this->addSql('ALTER TABLE hike_done ADD CONSTRAINT FK_94B46DD913D51EC0 FOREIGN KEY (hiker_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hike_done ADD CONSTRAINT FK_94B46DD9569FDE7D FOREIGN KEY (hikesdone_id) REFERENCES hike (hike_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE hike_done DROP CONSTRAINT FK_94B46DD913D51EC0');
        $this->addSql('ALTER TABLE hike_done DROP CONSTRAINT FK_94B46DD9569FDE7D');
        $this->addSql('DROP TABLE hike_done');
    }
}
