<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407141436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment (comment_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment_content TEXT NOT NULL, hike_id INT DEFAULT NULL, user_comment_id INT DEFAULT NULL, PRIMARY KEY (comment_id))');
        $this->addSql('CREATE INDEX IDX_9474526C71D4DE21 ON comment (hike_id)');
        $this->addSql('CREATE INDEX IDX_9474526C5F0EBBFF ON comment (user_comment_id)');
        $this->addSql('CREATE TABLE hike (hike_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hike_name VARCHAR(255) NOT NULL, hike_height INT DEFAULT NULL, hike_time INT NOT NULL, hike_leveel VARCHAR(15) NOT NULL, hike_length DOUBLE PRECISION NOT NULL, hike_family BOOLEAN NOT NULL, hike_description TEXT DEFAULT NULL, hike_thumbnail VARCHAR(50) DEFAULT NULL, location_id INT DEFAULT NULL, PRIMARY KEY (hike_id))');
        $this->addSql('CREATE INDEX IDX_2301D7E464D218E ON hike (location_id)');
        $this->addSql('CREATE TABLE location (location_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, location_name VARCHAR(150) NOT NULL, location_gps VARCHAR(150) NOT NULL, PRIMARY KEY (location_id))');
        $this->addSql('CREATE TABLE "user" (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_mail VARCHAR(180) NOT NULL, user_role JSON NOT NULL, user_password VARCHAR(255) NOT NULL, user_name VARCHAR(100) NOT NULL, user_firstname VARCHAR(100) NOT NULL, user_image VARCHAR(150) NOT NULL, user_description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (user_mail)');
        $this->addSql('CREATE TABLE user_hike (hike_user_id INT NOT NULL, user_hike INT NOT NULL, PRIMARY KEY (hike_user_id, user_hike))');
        $this->addSql('CREATE INDEX IDX_59809B2DF7E5A2C9 ON user_hike (hike_user_id)');
        $this->addSql('CREATE INDEX IDX_59809B2D59809B2D ON user_hike (user_hike)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C71D4DE21 FOREIGN KEY (hike_id) REFERENCES hike (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C5F0EBBFF FOREIGN KEY (user_comment_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE hike ADD CONSTRAINT FK_2301D7E464D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE user_hike ADD CONSTRAINT FK_59809B2DF7E5A2C9 FOREIGN KEY (hike_user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_hike ADD CONSTRAINT FK_59809B2D59809B2D FOREIGN KEY (user_hike) REFERENCES hike (hike_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C71D4DE21');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C5F0EBBFF');
        $this->addSql('ALTER TABLE hike DROP CONSTRAINT FK_2301D7E464D218E');
        $this->addSql('ALTER TABLE user_hike DROP CONSTRAINT FK_59809B2DF7E5A2C9');
        $this->addSql('ALTER TABLE user_hike DROP CONSTRAINT FK_59809B2D59809B2D');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE hike');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_hike');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
