<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260401073630 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hike (hike_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hike_name VARCHAR(255) NOT NULL, hike_height INT DEFAULT NULL, hike_time INT NOT NULL, hike_leveel VARCHAR(15) NOT NULL, hike_length DOUBLE PRECISION NOT NULL, hike_family BOOLEAN NOT NULL, hike_description TEXT DEFAULT NULL, hike_thumbnail VARCHAR(50) DEFAULT NULL, PRIMARY KEY (hike_id))');
        $this->addSql('CREATE TABLE "user" (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_name VARCHAR(100) NOT NULL, user_firstname VARCHAR(100) NOT NULL, user_image VARCHAR(150) NOT NULL, user_mail VARCHAR(100) NOT NULL, user_password VARCHAR(255) NOT NULL, user_description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_role JSON NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE hike');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
